# Generated by Django 4.2.20 on 2025-05-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_slide',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
