# Generated by Django 4.2.20 on 2025-05-04 15:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import order.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('discount_percent', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('expired', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('used_by', models.ManyToManyField(blank=True, related_name='used_coupons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Completed'), (4, 'Cancelled'), (5, 'Delivered')], default=1)),
                ('total_amount', models.BigIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ostan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('amar_code', models.IntegerField(verbose_name='Amar Code')),
            ],
            options={
                'verbose_name': 'Ostan',
                'verbose_name_plural': 'Ostans',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Shahrestan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('amar_code', models.IntegerField(verbose_name='Amar Code')),
                ('ostan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shahrestans', to='order.ostan', verbose_name='Ostan')),
            ],
            options={
                'verbose_name': 'Shahrestan',
                'verbose_name_plural': 'Shahrestans',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=15)),
                ('receiver_phonenumber', models.CharField(max_length=12, validators=[order.validators.IranianPhoneNumberValidator()])),
                ('ostan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ostan_addresses', to='order.ostan')),
                ('shahrestan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shahrestan_addresses', to='order.shahrestan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.BigIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='address_orders', to='order.useraddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coupon_orders', to='order.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
