# Generated by Django 4.2.20 on 2025-05-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'در انتظار پرداخت'), (2, 'در حال پردازش'), (3, 'اماده ارسال'), (4, 'لغو شده'), (5, 'تحویل داده شده')], default=1),
        ),
    ]
